name: E2E test
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      run: pytest
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: report
        path: reports/**
        retention-days: 30
    - name: Publish HTML report
      if: ${{github.ref == 'refs/heads/master' && success() || failure() }}
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: report
        publish_dir: ./reports
